name: Build, Scan, Sign, and Deploy

on:
  push:
    # branches: [ main ] - Test build on push

env:
  IMAGE_REPO: karankale/simple-time-service
  REGISTRY: docker.io

jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set IMAGE_TAG and IMAGE_NAME
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            BRANCH=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
            echo "IMAGE_TAG=${BRANCH}-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

          echo "IMAGE_NAME=${REGISTRY}/${IMAGE_REPO}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG src/

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Push Docker Image
        run: docker push $IMAGE_NAME:$IMAGE_TAG


